# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: UI Automation Suite

on:
  pull_request:
    branches: [ "main" ]
    paths: [ "./server/**" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./nightwatch-browserstack-sdk
    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Test Setup
      run: npm install
    - name: Run Local Suite
      env:
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      run: |
        cd ../server
        npm install
        node index.js &
        sleep 3
        cd ./nightwatch-browserstack-sdk
        npm run local_suite
